### ISSUE TITLE
The 'Add child' (m) operation from a subfolder takes the root folder instead of the current folder

### ISSUE THREAD

**Issue by irisida** [sendhil/vscode-file-explorer-menu#3]
**Issue description:**
When creating a child node from a sub-directory (empty) the plugin takes the root path instead of the directory which was the location where the selection of 'add child node' occurred.   

Assuming the following structure:
```
- src
--- dir1
--- dir2
--- dir3
``` 
if this directory structure is empty folders trying to add a child node the path will be 'src`. Once a file is added it will behave as expected and the path locations will handle the full path with subdirectories. 

```
- src
--- dir1
--- dir2
----- file 1
----- file 2
--- dir3        // if I choose child node from here (is highlighted in explorer) path is 'src/dir3/'
----- file 1
----- file 2 . // if I choose child node from here (is highlighted in explorer) path is full 'src/dir3/' 
```

**Expected Behaviour:**
I would expect adding child nodes even in an empty directories tree structure should respect the full path. 

**Actual behaviour:**
adding a file changes the behaviours. With an empty folder set, it seems to not pick up the path as expected. 

**What changed**
The plugin was working as expected, a change in settings to move the tree indent from the default 8 to 16 was performed and this was the side effect. Restart and add/delete a dummy file in the folder then repeat the exercise and it does not repeat so it is possible the plugin is thrown by settings changes being saved that relate to the tree/directories of a project. 

**disclaimer**
yes, it's a weird one.

**Comment by sendhil** [comment]
@irisida - thanks for the bug report. Will investigate.

**Comment by sendhil** [comment]
@irisida - trying to reproduce this locally but having trouble, does the following video look right to you? Also what OS are you on?

  
![Root Folder Bug](https://user-images.githubusercontent.com/437043/100419460-73436d80-3039-11eb-9866-b711cfc03b56.gif)

**Comment by irisida** [comment]
Yes that looks correct and what I'm typically getting/expect. I am on Mac 10.15.7

Only that I had a couple of occurrences where it would only pick up the root folder when the child folder was empty. Not every time. No memory issues. 

I'll try to get a video capture next time I see it.
