### ISSUE TITLE
Expose internal functions as commands

### ISSUE THREAD

**Issue by TommyDew42** [sendhil/vscode-file-explorer-menu#4]
First of all, great project! 👍 
No more mouses when navigating the file explorer ❤️ 

I am wondering if we can expose the internal functions as commands so that users can have keybindings to the functions?
For example, I would like to map "`a`" to `addChildNode()` and "`d`" to "`deleteChildNode(context)`".

**Comment by sendhil** [comment]
@TommyDew42 thanks! Need to test out [this](https://github.com/sendhil/vscode-file-explorer-menu/tree/expose-internal-functions-as-commands) branch before I publish.

**Comment by sendhil** [comment]
Apologies, today got away from me, will try to test it out in the next few days and then publish.

**Comment by TommyDew42** [comment]
@sendhil Thanks so much for the great work!

**Comment by sendhil** [comment]
@TommyDew42  - just published this to the marketplace.
